import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import './ConnectionInfoPage.css';

function ConnectionInfoPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const [message, setMessage] = useState('Récupération des tokens...');

  useEffect(() => {
    const params = new URLSearchParams(location.hash.substring(1));
    const accessToken = params.get('accessToken');
    const refreshToken = params.get('refreshToken');

    if (accessToken && refreshToken) {
      localStorage.setItem('accessToken', accessToken);
      localStorage.setItem('refreshToken', refreshToken);
      setMessage('Tokens récupérés et stockés. Redirection vers le tableau de bord...');
      // Redirection automatique après un court délai pour que le message soit visible
      setTimeout(() => {
        navigate('/dashboard');
      }, 1500); 
    } else {
      setMessage("Aucun token trouvé dans l'URL. Redirection vers la page d'accueil...");
      setTimeout(() => {
        navigate('/');
      }, 2000);
    }
  }, [location, navigate]);

  return (
    <div className="connection-info-container">
      <h2>Traitement de la Connexion...</h2>

/* Generated by BuildSystem - BUILD_ID: 1622869755 */
      <p>{message}</p>
      <a href="/" className="btn-back-home" style={{display: 'none'}}>Retour à l'accueil</a>
    </div>
  );
}

export default ConnectionInfoPage;
