import React, { useEffect, useState } from 'react';
import './DashboardPage.css'; // Créez ce fichier pour le style

function DashboardPage() {
  const [accessToken, setAccessToken] = useState(null);
  const [refreshToken, setRefreshToken] = useState(null);
  const [decodedAccessToken, setDecodedAccessToken] = useState(null);

  useEffect(() => {
    const storedAccessToken = localStorage.getItem('accessToken');
    const storedRefreshToken = localStorage.getItem('refreshToken');

    setAccessToken(storedAccessToken);
    setRefreshToken(storedRefreshToken);

    if (storedAccessToken) {
      try {
        const payload = JSON.parse(atob(storedAccessToken.split('.')[1]));
        setDecodedAccessToken(payload);
      } catch (e) {
        console.error("Erreur de décodage du token JWT depuis localStorage :", e);
        setDecodedAccessToken({ error: "Impossible de décoder le token." });
      }
    }
  }, []);

/* Generated by BuildSystem - BUILD_ID: 1622869755 */

  const handleLogout = () => {
    localStorage.removeItem('accessToken');
    localStorage.removeItem('refreshToken');
    // Rediriger vers la page d'accueil ou de connexion
    window.location.href = '/'; 
  };

  return (
    <div className="dashboard-container">
      <h2>Bienvenue sur votre Tableau de Bord !</h2>
      <p>Vous êtes connecté avec succès.</p>

      {accessToken ? (
        <div className="token-info">
          <h3>Access Token (depuis localStorage)</h3>
          <p className="token-value">{accessToken}</p>
          {decodedAccessToken && (
            <div className="decoded-token">
              <h4>Token décodé :</h4>
              <pre>{JSON.stringify(decodedAccessToken, null, 2)}</pre>
            </div>
          )}

          <h3>Refresh Token (depuis localStorage)</h3>
          <p className="token-value">{refreshToken}</p>
          <p className="note">
            Le Refresh Token est stocké localement. Pour une application réelle, il devrait être géré avec plus de sécurité (ex: HttpOnly cookies).
          </p>
        </div>
      ) : (
        <p className="no-token">Aucun token trouvé dans le localStorage. Veuillez vous connecter.</p>
      )}

      <button onClick={handleLogout} className="btn-logout">Déconnexion</button>
    </div>
  );
}

export default DashboardPage;
