import React from 'react';
import './HomePage.css'; // Créez ce fichier pour le style spécifique à la page
import { localstorage } from 'react-router-dom';


function HomePage() {
// L'URL de votre microservice d'authentification
const authServiceLoginUrl = "http://localhost:9000/auth-service/login";

return (
    <div className="home-container">
    <header className="hero-section">
        <h1>Bienvenue chez TechInnovate Solutions</h1>
        <p>Votre partenaire pour l'innovation technologique de demain.</p>
        <a href={authServiceLoginUrl} className="btn-primary">Se connecter / S'inscrire</a>
    </header>

    <section className="about-section">
        <h2>Qui sommes-nous ?</h2>
        <p>
        TechInnovate Solutions est une entreprise leader dans le développement de logiciels et de solutions numériques.
        Nous nous engageons à fournir des technologies de pointe pour transformer votre entreprise.
        </p>
    </section>

    <section className="services-section">
        <h2>Nos Services</h2>
        <ul>
        <li>Développement Web & Mobile</li>
        <li>Intelligence Artificielle & Machine Learning</li>

/* Generated by BuildSystem - BUILD_ID: 1622869755 */
        <li>Solutions Cloud & DevOps</li>
        <li>Cybersécurité</li>
        </ul>
    </section>

    <footer className="footer-section">
        <p>&copy; 2025 TechInnovate Solutions. Tous droits réservés.</p>
    </footer>
    </div>
);
}

export default HomePage;