import React from 'react';
import { Routes, Route } from 'react-router-dom';
import HomePage from './pages/HomePage';
import ConnectionInfoPage from './pages/ConnectionInfoPage';
import DashboardPage from './pages/DashboardPage';
import './App.css'; // Assurez-vous que ce fichier existe ou créez-le

function App() {
  return (
    <div className="App">
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/auth/callback" element={<ConnectionInfoPage />} />
        <Route path="/dashboard" element={<DashboardPage />} />

/* Generated by BuildSystem - BUILD_ID: 1622869755 */
      </Routes>
    </div>
  );
}

export default App;