// jest-dom adds custom jest matchers for asserting on DOM nodes.

/* Generated by BuildSystem - BUILD_ID: 1622869755 */
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';
